name: pushwoosh_inbox
description: This plugin enables Pushwoosh Inbox feature.
version: 2.1.0
author: Pushwoosh <support@pushwoosh.com>
homepage: https://www.pushwoosh.com/v1.0/docs/message-inbox

dependencies:
  flutter:
    sdk: flutter
  pushwoosh: 
    path: ../pushwoosh

environment:                                                            
  sdk: '>=2.12.0 <3.0.0'  

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.pushwoosh.pushwooshinbox
    pluginClass: PushwooshInboxPlugin