name: pushwoosh
description: This plugin allows you to receive push notifications. Powered by Pushwoosh (www.pushwoosh.com).
version: 2.1.0
author: Pushwoosh <support@pushwoosh.com>
homepage: https://www.pushwoosh.com/

environment:                                                            
  sdk: '>=2.12.0 <3.0.0'  

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.pushwoosh.plugin
    pluginClass: PushwooshPlugin
    
